// albums: load medium posts JSON (generated by CI) and render into #medium-posts
function renderMediumPosts(targetId='medium-posts') {
  const container = document.getElementById(targetId);
  if (!container) return;
  fetch('/assets/medium_posts.json')
    .then(r => r.ok ? r.json() : Promise.reject('no json'))
    .then(data => {
      const posts = data.posts || [];
      if (!posts.length) {
        container.innerHTML = '<div class="small">No recent posts yet — add some on Medium or enable the fetch workflow.</div>';
        return;
      }
      container.innerHTML = posts.map(p => `
        <div style="margin-bottom:12px">
          <a href="${p.link}" target="_blank" rel="noopener"><strong>${p.title}</strong></a>
          <div class="small">${p.excerpt} <span style="color:var(--muted)">· ${p.date ? new Date(p.date).toLocaleDateString() : ''}</span></div>
        </div>
      `).join('');
    })
    .catch(err => {
      console.warn('medium posts load failed', err);
      container.innerHTML = '<div class="small">Unable to load Medium posts automatically. You can add them manually.</div>';
    });
}

// Mobile navigation handler
document.addEventListener('DOMContentLoaded', function() {
  const mobileNav = document.getElementById('mobile-nav');
  if (mobileNav) {
    mobileNav.addEventListener('change', function() {
      if (this.value) {
        window.location.href = this.value;
      }
    });
  }
});

